png(filename = 'plot3.png', width = 480, height = 480, units='px')
plot(pwrcons$Timestamp,pwrcons$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_2,type="l",col="red")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_3,type="l",col="blue")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_2,type="l",col="red")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),lwd=c(1,1))
dev.off()