png(filename = 'plot4.png', width = 480, height = 480, units='px')
par(mfrow=c(2,2))
plot(pwrcons$Timestamp, pwrcons$Global_active_power,type="l",xlab="", ylab="Global Active Power")
plot(pwrcons$Timestamp,pwrcons$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(pwrcons$Timestamp,pwrcons$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_2,type="l",col="red")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_3,type="l",col="blue")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_2,type="l",col="red")
lines(pwrcons$Timestamp,pwrcons$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),lwd=c(1,1))
plot(pwrcons$Timestamp,pwrcons$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()